version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/etc/nginx/html
      - ./nginx/certs:/etc/nginx/certs
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nextcloud
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nextcloud: 
    container_name: zasx-nextcloud
    image: nextcloud:latest
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nextcloud
    ports:
      - "1000:80"
    volumes: 
      - nc-data:/var/www/html
    depends_on:
      - db

  torch:
    container_name: torch_jupyter
    build: jupyter
    runtime: nvidia
    command: jupyter notebook --notebook-dir=/workspace --ip='*' --no-browser --allow-root --NotebookApp.token=${PASSWORD}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /home/yuio/workspace/notebooks:/workspace
    ports:
      - "8888:8888"

  code-server:
    container_name: code-server
    build: code
    ports:
      - "8090:8080"
    user: 1000:1000
    volumes:
      - /home/yuio/workspace:/home/coder/projects
      - /opt:/opt

      - /home/yuio/zasx/code/config:/home/coder/.config
      - /home/yuio/zasx/code/bashrc:/home/coder/.bashrc

      - code-data:/home/coder/.local
    environment:
      - PASSWORD=${PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  code-data:
  db-data:
  nc-data:
